### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by ilovecv** [ZhiHanZ/IRIS0-SPAN#1]
Hi,

Thanks for sharing your codes. I cound not run the training successfully since some files are missing, like layers. Could you please also share the rest codes? Thanks.

**Comment by ZhiHanZ** [comment]
Hi,
The script seems to work normaly on my side. Could you provide the script you were using and the error information please? Thanks

**Comment by ilovecv** [comment]
Hi, 
The layers file to define the Encoder, Decoder is missing: https://github.com/ZhiHanZ/IRIS0-SPAN/blob/main/models/ManTraNetv3.py#L22
Also some util files are missing: https://github.com/ZhiHanZ/IRIS0-SPAN/blob/main/trainer.py#L57

Thanks for your reply.

**Comment by Sh1p-wy** [comment]
I also encountered the same problem

**Comment by michiganleon** [comment]
Thanks for pointing out the issue. There indeed are some missing files. We will upload the necessary files as soon as possible at some point next week. Thanks for your patience.

**Comment by ilovecv** [comment]
Thanks. Looking forward to it!

**Comment by ZhiHanZ** [comment]
Hi there:
I have already add the missing file to the repo, and tested them in our lab's computer, everything works, if there are any other questions, feel free to tell us.
For Encoder and Decoder part, we have experienced them before and now we decided to remove it from code base because it seems to be unneeded

**Comment by ilovecv** [comment]
Hi, 
Thanks for the quick updates. However, maybe there are still some files missing. 
https://github.com/ZhiHanZ/IRIS0-SPAN/blob/main/models/ManTraNetv3.py#L23

from layers.MyLayers import *
ModuleNotFoundError: No module named 'layers'

**Comment by ZhiHanZ** [comment]
> Hi,
> Thanks for the quick updates. However, maybe there are still some files missing.
> https://github.com/ZhiHanZ/IRIS0-SPAN/blob/main/models/ManTraNetv3.py#L23
> 
> from layers.MyLayers import *
> ModuleNotFoundError: No module named 'layers'

I have already updated layers module

**Comment by ilovecv** [comment]
Hi @ZhiHanZ ,

I can run the codes successfully now. 
For the shared model weight PixelAttention32.h5, is it the pretrained model?
Another question is given the predicted mask, may I know if there are any ways to convert it to binary classification decision, i.e., authentic or tampered? 

Thank you very much!

**Comment by michiganleon** [comment]
@ilovecv Thanks for the update. 
I saw on previous comment you mention you got lower AUC, is that resolved? If not, could you describe how did you get that score (is there any fine-tuning, how did you use the dataset/evaluation function, etc.)
If there is no upload mistake, PixelAttention32.h5 is supposed be the model we reported in the paper that is pre-trained with the synthesis dataset provided by ManTraNet. 

For classification. SPAN is not designed for image level anomaly classification. But maybe you can consider the following ways:
- We are using the pre-trained feature extractor from ManTraNet and we did not update its weight. In ManTraNet it provides a classification head that connects to the feature extractor. You can try to use that (or just directly use the ManTraNet to do classification, should have the same result).
- Its not clear if the anomaly localization module (SPAN's major novelty) will give better classification feature. But if you are interested you can try to replace the final few layers of SPAN to some classification head and fine-tune it on the required dataset with classification ground truth.
-  You can also try to calculate the max/sum of the final prediction map and use some threshold to make classification decision but my guess is it will have poor performance.

**Comment by ilovecv** [comment]
@michiganleon Thanks for your quick response.

> I saw on previous comment you mention you got lower AUC, is that resolved? If not, could you describe how did you get that score (is there any fine-tuning, how did you use the dataset/evaluation function, etc.)
If there is no upload mistake, PixelAttention32.h5 is supposed be the model we reported in the paper that is pre-trained with the synthesis dataset provided by ManTraNet.

There were some mistakes on my side. I have corrected them and got similar numbers as reported in your paper. Just want to double check with you if this is the pretrained model:)

> For classification. SPAN is not designed for image level anomaly classification. But maybe you can consider the following ways:
We are using the pre-trained feature extractor from ManTraNet and we did not update its weight. In ManTraNet it provides a classification head that connects to the feature extractor. You can try to use that (or just directly use the ManTraNet to do classification, should have the same result).

ManTraNet only predicts the mask, I think there is no classificatin head? I am curious why you froze the feature extractor and didn't train the network end-to-end? Also in your paper, you mentioned your resized the feature to a fixed size of 224x224. Why do we need the fixed feature size input?

> Its not clear if the anomaly localization module (SPAN's major novelty) will give better classification feature. But if you are interested you can try to replace the final few layers of SPAN to some classification head and fine-tune it on the required dataset with classification ground truth.

I will try it!

> You can also try to calculate the max/sum of the final prediction map and use some threshold to make classification decision but my guess is it will have poor performance.

I have tried it, the performance was poor.

**Comment by michiganleon** [comment]
@ilovecv 
1, The feature extractor in ManTraNet was trained with a 385-way manipulation classification task so there is a classification head, please check their paper for more details. 
2, Yes we froze the feature extractor because training end-to-end hurts the performance a little bit (according to ManTraNet author's experience).
3, The SPAN detection module seems to work stable with a fixed canvas size.

**Comment by ilovecv** [comment]
@michiganleon 
Thank you very much for your reply. For current training standard, I found only forged images are used. If I add authentic images for training with all zero masks, will it improve the performance?  

Another question is do you plan to share the synthetic image manipulation datasets used in the pretraining step?

Thank you very much!

**Comment by ZhiHanZ** [comment]
issue closed due to inactivity
